### ISSUE TITLE
Implement Healing of Plastic Strain

### ISSUE THREAD

**Issue by arijitlaik** [rbeucher/UWGeodynamics#21]
Linear and or exponential healing of accumulated plastic strain plastic over a user assigned time period.
Should be relatively simple/trivial?, could try implementing myself

**Comment by rbeucher** [comment]
Yes it is easy:
Something like:
strain*(1.0-time/tau)

with tau the decay value.
I could add that to the material class so that healing is material dependent..
R

**Comment by rbeucher** [comment]
But that's a very simplistic approach.

**Comment by arijitlaik** [comment]
More complex temperature dependent implementation could be put up later, it would be fine , something like material.tau_healing would do great.

**Comment by rbeucher** [comment]
Hi @arijitlaik 
See ed2d3f2

Romain
