### ISSUE TITLE
Variable traction field at the side walls

### ISSUE THREAD

**Issue by ofbodur** [rbeucher/UWGeodynamics#27]
Hello,

Is it possible that I define specific traction field magnitudes for each mesh node number in the left and right side walls?

I tried something like this,

appliedTractionField=PoiseuilleFlowModel.mesh.add_variable(nodeDofCount=2)

appliedTractionField.data[:,0]=0.00

.. Then I assign pressures to appliedTractionField.data array with some values having dimensions (Pascal) corresponding to the mesh node numbers of the side walls. Then I non-dimensionalise the array for further use, and do the following:

```
PoiseuilleFlowModel.set_velocityBCs(left=[appliedTractionField.data[PoiseuilleFlowModel.mesh.specialSets["MinI_VertexSet"].data[:],0] * GEO.Dimensionalize(1.0, u.pascal) ,0.0 * GEO.Dimensionalize(1.0, u.pascal)],
   							     right=[appliedTractionField.data[PoiseuilleFlowModel.mesh.specialSets["MaxI_VertexSet"].data[:],0] * GEO.Dimensionalize(1.0, u.pascal) ,0.0 * GEO.Dimensionalize(1.0, u.pascal)],
   							     top=[0.0 * u.centimeter / u.year, 0.0 * u.centimeter / u.year],
   							     bottom=[None, 0.0 * u.centimeter / u.year])
```

but seems that I am doing it wrong..

**Comment by rbeucher** [comment]
Hi Omer,

I thought I had a Poiseuille example somewhere but I can not find it. I will see if I can make one.
In the meantime have a look at UWGeodynamics/examples/1_20_ColumnsTractionBottom.ipynb
It is very similar.

Romain

**Comment by rbeucher** [comment]
If you want to change the condition along the wall you can do it using the indexSet parameter inside the set_velocityBCs function. You create a set of nodes to which you apply a condition with units of stress.
There are many ways to do what you want to do...

**Comment by ofbodur** [comment]
Thanks Romain,

Ok, how can i create a pre-defined FeMesh_IndexSet with nodes that are of interest to me?
in set_velocityBCs function, indexSet=Array does not work, so it should be type of FeMesh_IndexSet I guess?

**Comment by rbeucher** [comment]
Have a look at the Indentor Benchmark in "examples" (dev branch). Iterating is usually a bad idea. Use a function instead.

**Comment by rbeucher** [comment]
The less for loop the better... LOL

**Comment by ofbodur** [comment]
Hello again Romain,

I have been working on the code after your advice.
I need to define specific pressures at each node, and I had to define boundary conditions in a for-loop, to different nodes each time through iteration. Here is the code I ended up:



```
indexSetLeft = {}
indexSetRight = {}

for index in range(0,50,1):
    thecondLeft=PoiseuilleFlowModel.mesh.data[PoiseuilleFlowModel._left_wall.data][:,1]==PoiseuilleFlowModel.mesh.data[PoiseuilleFlowModel._left_wall.data][index,1]
    indicesLeft=PoiseuilleFlowModel._left_wall.data[thecondLeft]
    indexSetLeft["L" + str(index)] =GEO.uw.mesh.FeMesh_IndexSet(PoiseuilleFlowModel.mesh,topologicalIndex=0,size=PoiseuilleFlowModel.mesh.nodesGlobal,fromObject=indicesLeft)
    
    thecondRight=PoiseuilleFlowModel.mesh.data[PoiseuilleFlowModel._right_wall.data][:,1]==PoiseuilleFlowModel.mesh.data[PoiseuilleFlowModel._right_wall.data][index,1]
    indicesRight=PoiseuilleFlowModel._right_wall.data[thecondRight]
    indexSetRight["R" + str(index)] =GEO.uw.mesh.FeMesh_IndexSet(PoiseuilleFlowModel.mesh,topologicalIndex=0,size=PoiseuilleFlowModel.mesh.nodesGlobal,fromObject=indicesRight)
    
    PoiseuilleFlowModel.set_velocityBCs(bottom=[None, 0.0], top=[0.0, 0.0], 
                                    indexSets=[(
                                        [LeftWallPressureNew2[index]* GEO.Dimensionalize(1.0, u.pascal),None],indexSetLeft[('L' + str(index))]
                                    )]
                                       )
    PoiseuilleFlowModel.set_velocityBCs(bottom=[None, 0.0], top=[0.0, 0.0], 
                                    indexSets=[(
                                        [RightWallPressureNew2[index]* GEO.Dimensionalize(-1.0, u.pascal),None],indexSetRight[('R' + str(index))]
                                    )]
                                       )
```

My question is, when I define the boundary conditions for specific indexSets, and redefine it for different indeSets, does it overwrite? 
I can share the whole code if you like,
Cheers

**Comment by rbeucher** [comment]
A minimal example (if I correctly understand what you are doing)

```python
import UWGeodynamics as GEO

u = GEO.UnitRegistry

Model = GEO.Model(elementRes=(192, 64), 
                  minCoord=(0. * u.kilometer, -110. * u.kilometer), 
                  maxCoord=(360. * u.kilometer, 10. * u.kilometer), 
                  gravity=(0.0, -9.81 * u.meter / u.second**2))


LeftBot50 = GEO.uw.mesh.FeMesh_IndexSet(Model.mesh,topologicalIndex=0,
                                    size=Model.mesh.nodesGlobal,
                                    fromObject=Model._left_wall.data[:50]) 

RightBot50 = GEO.uw.mesh.FeMesh_IndexSet(Model.mesh,topologicalIndex=0,
                                    size=Model.mesh.nodesGlobal,
                                    fromObject=Model._right_wall.data[:50]) 

Model.set_velocityBCs(indexSets=[([-1. * u.centimetre / u.year, None], LeftBot50),
                                ([-1. * u.centimetre / u.year, None], RightBot50)])

Fig = Model.plot.velocityField(figsize=(1200,400))

```

UWGeo is meant to be simple, If you have more than 3 lines to do what you want, there is something wrong...

Also. Forget about the "for loops" when you can!!!

**Comment by ofbodur** [comment]
Hello Romain,

I would like to use UWGeodynamics in my problem, as it gives me a nice way of dealing with rheologies and other useful things.

Yes, I need to define traction boundary condition at each node of the side walls, because i need to apply pressures greater than of the lithostatic pressure of the node of interest, so the material will be slightly under higher pressure to the x-direction and I would end up with pressure driven flow. If I apply a constant pressure to the side wall, then I will end up with higher velocities at top and lower velocities at the bottom due to the increase in lithostatic pressure with depth. Therefore, I had to use for loop for this problem. 

Do you have any UWGeodynamics solution for that?
Cheers
Omer

**Comment by rbeucher** [comment]
Try something like that:

```python
import UWGeodynamics as GEO

u = GEO.UnitRegistry

Model = GEO.Model(elementRes=(192, 64), 
                  minCoord=(0. * u.kilometer, -110. * u.kilometer), 
                  maxCoord=(360. * u.kilometer, 10. * u.kilometer), 
                  gravity=(0.0, -9.81 * u.meter / u.second**2))

Model.set_mechanicalBCs(left=[20. * u.megapascal, None],
                                      right=[10. * u.megapascal, None])

```

**Comment by rbeucher** [comment]
Note that you are going to need Dirichlet conditions for it to work. I don't have anything to visualize stresses yet...

**Comment by ofbodur** [comment]
Thanks a lot Romain, I will let you know how I progress on that.

**Comment by rbeucher** [comment]
I will be at Sydney Uni on  july 4th, 5th, 6th Omer\

**Comment by ofbodur** [comment]
Thanks Romain, we can discuss in detail when you are in Sydney. 

By the way,

1) What is the dimension of velocity field magnitude for the most recent dev. version of UWGeodyanmics? 
2) What does boundariesField stand for?

Thanks,
Omer

**Comment by rbeucher** [comment]
What do you mean the dimension? Units? 
Where have you seen boundariesField ?

**Comment by rbeucher** [comment]
ah, My bad. BoundariesField, is used to visualise the boundary conditions. I used that to check them.
I will probably remove it.

**Comment by ofbodur** [comment]
Thanks a lot Romain.
Cheers
Omer

**Comment by ofbodur** [comment]
Hello Romain,
here is a very simple version of the problem:

```
import UWGeodynamics as GEO
import numpy as np
import glucifer

Model = GEO.Model(minCoord=(-1. * u.kilometer, -1. * u.kilometer),
                  maxCoord=(1. * u.kilometer, 1. * u.kilometer),  
                  elementRes=(2, 2), gravity=(0.0, -9.8 * u.meter / u.second**2))

```
Now, I will define pressures at each 3 nodes of left and right walls by using the following:
```
indexSetLeft = {}
indexSetRight = {}
for index in range(0,3,1):
    indexSetLeft["L" + str(index)] = GEO.uw.mesh.FeMesh_IndexSet(Model.mesh,topologicalIndex=0,
                                    size=Model.mesh.nodesGlobal,
                                    fromObject=Model._left_wall.data[index]) 
    
    indexSetRight["R" + str(index)] = GEO.uw.mesh.FeMesh_IndexSet(Model.mesh,topologicalIndex=0,
                                    size=Model.mesh.nodesGlobal,
                                    fromObject=Model._right_wall.data[index]) 

```
If you run the following code, you will see that I assigned 1 node to each. These nodes are at the left wall.
`indexSetLeft["L" + str(0)],indexSetLeft["L" + str(1)],indexSetLeft["L" + str(2)]`

Same for the right wall:
`indexSetRight["R" + str(0)],indexSetRight["R" + str(1)],indexSetRight["R" + str(2)]`

Now, I will define my boundary conditions as follows:

```
Model.set_velocityBCs(top=[0.0 * u.centimeter / u.year, None],bottom=[None,0.0 * u.centimeter / u.year],
                        indexSets=[([1 * u.megapascal, None],  indexSetLeft["L" + str(0)]),
                                   ([1 * u.megapascal, None],  indexSetLeft["L" + str(1)]),
                                   ([1 * u.megapascal, None],  indexSetLeft["L" + str(2)]),
                                   ([1 * u.megapascal, None],  indexSetRight["R" + str(0)]),
                                   ([1 * u.megapascal, None],  indexSetRight["R" + str(1)]),
                                   ([1 * u.megapascal, None],  indexSetRight["R" + str(2)])])

```

Now, what I get after running the code above is that I defined Dirichlet boundary conditions. There is no Neumannn BC.

`[<underworld.conditions._conditions.DirichletCondition at 0x7fbef00da510>]`

So, something is wrong..
Omer

**Comment by rbeucher** [comment]
That's because you are running the master branch. The indexSet has not been merged into master yet. 
Use development Omer.

**Comment by ofbodur** [comment]
You are legend! problem solved.
Cheers
Omer

**Comment by ofbodur** [comment]
Hello Romain,

Thanks for your help today. I have been working on a simple model. I tried to make a conditional function to be called by the boundary conditions, but it seems I could not achieve it. Here is the code I tried:

```
BasePressure=3038245000.0
BasePressure2=BasePressure+(3300*9.8*100000)

P_added=200000.0*5.0


NeumannConditionsLeft=fn.branching.conditional([ (PoiseuilleFlowModel.y >-101.0 * u.kilometer, 0.0 * u.centimeter / u.year),
                                                (True, BasePressure2+P_added * u.megapascal)])

NeumannConditionsRight=fn.branching.conditional([ (PoiseuilleFlowModel.y >-101.0 * u.kilometer, 0.0 * u.centimeter / u.year),
                                                 (True, (-1.0)*(BasePressure2+P_added) * u.megapascal)])




PoiseuilleFlowModel.set_velocityBCs(bottom=[None, 0. * u.centimetre / u.year],
                                    top=[None,None],
                                    left=[NeumannConditionsLeft,None],
                                    right=[NeumannConditionsRight,None])
```
Then, I got the following error:

```
ValueErrorTraceback (most recent call last)
<ipython-input-26-7b88dceb5ad6> in <module>()
      5 
      6 
----> 7 NeumannConditionsLeft=fn.branching.conditional([ (PoiseuilleFlowModel.y >-101.0 * u.kilometer, 0.0 * u.centimeter / u.year),
      8                                                 (True, BasePressure2+P_added * u.megapascal)])
      9 NeumannConditionsRight=fn.branching.conditional([ (PoiseuilleFlowModel.y >-101.0 * u.kilometer, 0.0 * u.centimeter / u.year),

/opt/underworld2/underworld/function/_function.pyc in __gt__(self, other)
    435 
    436         """
--> 437         return greater( self, other )
    438 
    439     def __ge__(self,other):

/opt/underworld2/underworld/function/_function.pyc in __init__(self, fn1, fn2, **kwargs)
    987         if not isinstance( fn1fn, Function ):
    988             raise TypeError("Functions must be of type (or convertible to) 'Function'.")
--> 989         fn2fn = Function.convert( fn2 )
    990         if not isinstance( fn2fn, Function ):
    991             raise TypeError("Functions must be of type (or convertible to) 'Function'.")

/opt/underworld2/underworld/function/_function.pyc in convert(obj)
    190                                                          +"'bool' (and iterables of these types) are convertible "
    191                                                          +"to functions.\n\n"
--> 192                                                          +"Original encountered exception message:\n")
    193 
    194 

/opt/underworld2/underworld/function/_function.pyc in convert(obj)
    160             try:
    161                 # first try convert directly to const type object
--> 162                 return misc.constant(obj)
    163             except Exception as e:
    164                 # ok, that failed, let's now try convert to vector of function type object

/opt/underworld2/underworld/function/misc.pyc in __init__(self, value, *args, **kwargs)
     51 
     52         # lets try and convert
---> 53         self._ioguy = self._GetIOForPyInput(value)
     54         self._value = value
     55         self._fncself = _cfn.Constant(self._ioguy)

/opt/underworld2/underworld/function/misc.pyc in _GetIOForPyInput(self, value)
     91                 raise ValueError("'value' object provided to Constant Function constructor does not appear to be valid. "
     92                                 +"Only python types 'int', 'float' and 'bool' are acceptable, or iterable objects "
---> 93                                 +"homogeneous in these types.")
     94             else:
     95                 # iterable

ValueError: An exception was raised while try to convert an object to an Underworld2 function. Usually this occurs because you didn't pass in the correct object. Please check your function arguments! Note that only python types 'int', 'float' or 'bool' (and iterables of these types) are convertible to functions.

Original encountered exception message:

'value' object provided to Constant Function constructor does not appear to be valid. Only python types 'int', 'float' and 'bool' are acceptable, or iterable objects homogeneous in these types.
                                    
```

Is it because PoiseuilleFlowModel.y does not give integers?

**Comment by arijitlaik** [comment]
@ofbodur 
non dimensionalize the terms in the boundary conditions, use GEO.nd(100.0*u.megapascal) or something, for an example
'''
tapeL=frictionalBasalLayer
flthick=GEO.nd(tapeL.top-tapeL.bottom)
conditions = [(Model.y <= GEO.nd(rigidBase.top), GEO.nd(-velocity)),
              (Model.y < GEO.nd(tapeL.top),
               GEO.nd(-velocity)*(flthick-(Model.y-GEO.nd(tapeL.bottom)))/flthick),
              (True, GEO.nd(0. * u.centimeter / u.year))]

VelocityBcs = Model.set_velocityBCs(
    left=[conditions, 0.],
    right=[-velocity, None],
    top=[None, None],
    bottom=[-velocity, 0.])

'''

**Comment by ofbodur** [comment]
Hello @arijitlaik Thanks for you comment, 

now it seems to working after nondimensionalizing the BC's :)
Cheers
Omer

**Comment by ofbodur** [comment]
Hello Romain,

The projStressField.h5 output has no units. How can I make it Pascal?

Cheers
Omer

**Comment by rbeucher** [comment]
Different pb Omer, start a new issue please so that everyone can see it.
