### ISSUE TITLE
UWGeodynamics on Raijin

### ISSUE THREAD

**Issue by ofbodur** [rbeucher/UWGeodynamics#31]
Hello Romain,

When I execute the pbs script you recently provided in 3D_rift, UWGeodynamics is not found in my directories. 
```
import UWGeodynamics as GEO
    raise ImportError("Can not find Underworld, please check your installation")

```
When I check the pbs script, it says:
```
#UW_DIR=$HOME/programs/underworld2_master # master branch
UW_DIR=$HOME/programs/underworld2_development # Development branch

```
So, I don't have underworld2_development branch in my home directory. How can I install it?

By the way I already have UWGeodynamics in /home/562/ofb562/opt/ but maybe it is the old one.. 

So, could you please help me to update my directories and be able to run some UWGeodyanamics models on Raijin?
Thanks

**Comment by rbeucher** [comment]
It can not find Underworld. 
There is a version at /short/q97/rb5533.
My advice is to create a symlink in your home:

```bash

cd $HOME
mkdir -p programs
cd programs
ln -s underworld2_master /short/q97/Underworld/underworld_master_05_28_2018
```
As for UWGeo, read the manual and install it in your home.

Romain

**Comment by rbeucher** [comment]
I am closing this Omer. Feel free to open it if needed.

**Comment by ofbodur** [comment]
Hello Romain,
I tried it, but I have permission problem:
`
ln: creating symbolic link `/short/q97/Underworld/underworld_master_05_28_2018/underworld2_master': Permission denied`

Is there any other way around? By the way, I need to have the dev_ version
Cheers
Omer

**Comment by rbeucher** [comment]
My bad

```bash

cd $HOME
mkdir -p programs
cd programs
ln -s  /short/q97/Underworld/underworld_master_05_28_2018 underworld2_master
```

**Comment by rbeucher** [comment]
There is also a dev version. create a link to the dev if you want the dev

**Comment by ofbodur** [comment]
Thanks Romain,

I am using the development version now (05_28_2018)
However, the following code is not working in the version I have in my UWGeodynamics directory in Raijin even though I updated UWGeodynamics using the following:

`pip install UWGeodynamics --user --upgrade`

```
crust.density  = GEO.LinearDensity(reference_density=2600. * u.kilogram / u.metre**3,
Traceback (most recent call last):
    crust.density  = GEO.LinearDensity(reference_density=2600. * u.kilogram / u.metre**3,
AttributeError: 'module' object has no attribute 'LinearDensity'

```

**Comment by rbeucher** [comment]
delete your installation of UWGeo, clone the new version and install it.

**Comment by rbeucher** [comment]
Don't use pip on raijin Omer. Just reinstall it from source.
look at the manual:

https://github.com/rbeucher/UWGeodynamics/wiki/Local_install

**Comment by ofbodur** [comment]
thanks Romain,

If I follow the page you sent, it says use the following:

` pip install UWGeodynamics --user`

How can i install without pip? 
Thanks

**Comment by rbeucher** [comment]
Read the second option. Install from source...

**Comment by rbeucher** [comment]
I have  pushed the latest version on pypi. pip should work.

**Comment by ofbodur** [comment]
Thanks Romain, I installed it from source,

but now I have this problem...

`    shape=GEO.shapes.Layer(top=68.0 * u.kilometer, bottom=0.0 * u.kilometer))`

**Comment by rbeucher** [comment]
"""Layer is deprecated, use Layer2D or Layer3D instead"""

**Comment by ofbodur** [comment]
Hello Romain,

Ok, I changed them and it works fine now. 

However, there is sth that I quite don't understand.
The following code should produce an array of lithostatic pressures:

`P, bottomPress = PoiseuilleFlowModel.get_lithostatic_pressureField()`

However, the array P is empty when I run in Raijin, but it works fine in my desktop.

**Comment by rbeucher** [comment]
Is it empty or does it return nothing?

**Comment by ofbodur** [comment]
Hello Romain,

The model script is here:
`/short/q97/ofb562/PoiseuilleFlow_Lith/Omer_PF_27July.py`

The pbs script is here:
`/short/q97/ofb562/PoiseuilleFlow_Lith/pbs_script_RB`

**Comment by rbeucher** [comment]
Sorry Omer, I had a quick look and there are too many things going on. I can't spend time on that today.
Simplify it. Try to isolate the pb and then will see. Careful when you manipulate things in parallel though...

**Comment by ofbodur** [comment]
Ok Thanks Romain,

I will do my best :)

Cheers
