### ISSUE TITLE
Stress Field output unit

### ISSUE THREAD

**Issue by ofbodur** [rbeucher/UWGeodynamics#36]
Hello Romain,

The projStressField.h5 output has no units. How can I make it Pascal?
and, it would be cool if I had the 2nd invariant of the deviatoric stress tensor as another output :)
Cheers
Omer

**Comment by rbeucher** [comment]
You can define the output units of any fields using

```python
GEO.rcParams["field.SIunits"] = GEO.u.units
```
so for the projStressField field:

```python
GEO.rcParams["projStressField.SIunits"] = u.pascal
```
I have changed the code so the stress field units defaults to pascal...

**Comment by rbeucher** [comment]
As for the second invariant... it's a different pb.. LOL new issue!

**Comment by rbeucher** [comment]
```python
import underworld.function as fn

fn.tensor.second_invariant(projStressField)
```

**Comment by rbeucher** [comment]
Update the code.

**Comment by ofbodur** [comment]
Is it Ok if i use the development version?

**Comment by rbeucher** [comment]
yes
