### ISSUE TITLE
2nd Invariant of the Deviatoric Stress Tensor

### ISSUE THREAD

**Issue by ofbodur** [rbeucher/UWGeodynamics#37]
Hello Romain,

I learned that I can calculate it using the following:

```
import underworld.function as fn
fn.tensor.second_invariant(projStressField)

```

How can i make sure that I will have that output in all checkpoints?

**Comment by rbeucher** [comment]
We are working on it. @arijitlaik

**Comment by rbeucher** [comment]
If you want to have it calculated and save it at each checkpoint you can create a meshVariable and write a function that you include in the Model.postSolveHook.
Have a look at the doc for both Underworld and UWGeo

**Comment by arijitlaik** [comment]
A simple example for the yield stress from Drunker Prager Criterion
'''
YieldMap = {}
YieldStressFn = None
for material in Model.materials:

    YieldMap[material.index] = 0.

    if material.plasticity:

        YieldHandler = material.plasticity
        YieldHandler.pressureField = Model.pressureField
        YieldHandler.plasticStrain = Model.plasticStrain

        if Model.mesh.dim == 2:
            yieldStress = YieldHandler._get_yieldStress2D()
        if Model.mesh.dim == 3:
            yieldStress = YieldHandler._get_yieldStress3D()
        YieldMap[material.index] = yieldStress

YieldStressFn = GEO.uw.function.branching.map(fn_key=Model.materialField,mapping=YieldMap)

figYt = glucifer.Figure(
    figsize=figSize,
    quality=3,
    title="Yield Stress Map, megapascal",
    boundingBox=((GEO.nd(Model.minCoord[0]), GEO.nd(Model.minCoord[1])),
                 (GEO.nd(Model.maxCoord[0]), GEO.nd(Model.maxCoord[1]))))

def saveFigures():
   figYt.save(Model.outputDir+'/YieldStress' + str(stepModel).zfill(4) + '.png')

Model.postSolveHook = saveFigures

'''

**Comment by rbeucher** [comment]
Great example @arijilaik thanks

**Comment by arijitlaik** [comment]
@rbeucher could we add the 2nd Invariant of the Deviatoric Stress Tensor as  possible plot option?

**Comment by rbeucher** [comment]
We could, I want to clean up that viscosityFn monster first... It's ugly and almost impossible to follow...

**Comment by rbeucher** [comment]
I have added it to the code. projStressField return the stress field on the mesh.
plot.stressField plot the stressField, it is checkpointed. I have removed the tensor though... 
It is still available but will not checkpoint by default.

**Comment by ofbodur** [comment]
Thanks a lot Romain, I will update my image on docker, run a model, and look at the outputs.
Cheers
Omer
