### ISSUE TITLE
Adding a thermal anomaly at t=0 Myr

### ISSUE THREAD

**Issue by ofbodur** [rbeucher/UWGeodynamics#41]
Hello Romain,

I plan to add a thermal anomaly defined by a rectangle in the asthenosphere. This rectangle is another material defined by a polygon shape. 

I was wondering when we set the temperature boundary conditions, and reach the steady state temperature solution, does this temperature boundary conditions continue to be active during model run? Can I define temperature boundary conditions for the "model run" and initial temperature for the rectangle in my asthenosphere having 100 Kelvin higher than the background.

```
PoiseuilleFlowModel.set_temperatureBCs(top=293.15 * u.kelvin, 
                         bottom=1626.15 * u.kelvin,
                         materials=[(asthenosphere, 1626.15 * u.kelvin),(air, 293.15 * u.kelvin),(anomaly,1626.15 * u.kelvin)])
```

`PoiseuilleFlowModel.init_model()`

`PoiseuilleFlowModel.temperature.data[PoiseuilleFlowModel.projMaterialField.data[:]==5]=GEO.nd(1726.0 * u.kelvin)`

I was doing this routine in UW1 by calling the steady-state temperatures (TemperatureField.###.h5) in lmrInitials.xml and defining a hotter region on top that steady-state solution to model the thermal anomaly. At the same time, i could define other temperature BC as i like.

**Comment by ofbodur** [comment]
Oh Ok, so I can define it again before model run?

**Comment by HanyMKhalil** [comment]
Hi ofbodur , Romain

I saw this post and its quite interest could you please elaborate more on it? I want to add a plume weakness at the base of the lithosphere so I created a spherical shape as a new material (I couldnot find a way to create a hemispherical shape if you have any ideas?) and I only assigned a temperature for it in the Temperature BC, but after model init I desplayed the temperature gradient and it doesnot seem to have any temperature anomaly in the isotherms? what I am doing wrong ??

**Comment by ofbodur** [comment]
> Hi ofbodur , Romain
> 
> I saw this post and its quite interest could you please elaborate more on it? I want to add a plume weakness at the base of the lithosphere so I created a spherical shape as a new material (I couldnot find a way to create a hemispherical shape if you have any ideas?) and I only assigned a temperature for it in the Temperature BC, but after model init I desplayed the temperature gradient and it doesnot seem to have any temperature anomaly in the isotherms? what I am doing wrong ??

Hi HanyMKhalil, 
Perhaps your newly created spherical shape is being overwritten by the ambient mantle or another material. You better check that first. After setting the temperature stabilisation by ModelName.init_model(), you may consider accessing the temperature field (from the h5 files) and if you figure out how to access those elements in the spherical model, then you can modify the values of those elements before you actually run your model. Then, perhaps it's better not to define a constant temperature to any mantle material other than boundaries so that your manual modification of the temperature is effective and not overwritten by the temperature boundary conditions. Hope that helps.

**Comment by HanyMKhalil** [comment]
Hi Ofbodur,

Thanks alot I will try to not define a specific value for the mantle, however I donot think i know how to access and modify the teperature on the mesh where I defined the spherical shape since I am using UWgeodynamics no much I can do.

I just created a spehrical shape in the model material and then in BC i defined its temperature in this way:

Model.set_temperatureBCs(top=293.15 * u.degK, 
                         bottom=1393.15 * u.degK, 
                         materials=[(mantle, 1393.15 * u.degK), (air, 293.15 * u.degK), (plume, 1893.15 * u.degK)])


shall I remove the part where i fixed the temperature of the mantle??

**Comment by ofbodur** [comment]
Hi HanyMKhalil, 

As you will see from Romain's comment above, you can change the boundary conditions after you initialise the temperature field, and in that step where you redefine the boundary conditions, I would recommend removing the part where you fix the temperature of the mantle.

That said, I was using UW1 so I do not know if this solution will apply to UWGeodynamics.

**Comment by patrice-rey** [comment]
Hi HanyMKhalil,
Make sure that your temperature clips are after the Model.init_model() which initialises the temperature field.
