### ISSUE TITLE
Nonlinear iterate tolerance

### ISSUE THREAD

**Issue by ofbodur** [rbeucher/UWGeodynamics#43]
Hello Romain,

When I do the following:

`GEO.rcParams["nonlinear.tolerance"]=0.2`

The model still takes the tolerance value as 0.01 which is the default value.

Why is that so?
Omer

**Comment by arijitlaik** [comment]
set initial tolerance tool 
```
GEO.rcParams["nonlinear.tolerance"] = 1e-3
GEO.rcParams["nonlinear.max.iterations"]=200
GEO.rcParams["nonlinear.min.iterations"]=3
GEO.rcParams["initial.nonlinear.tolerance"]=1e-3
GEO.rcParams["initial.nonlinear.max.iterations"]=20
```

**Comment by ofbodur** [comment]
@arijitlaik thanks a lot, it is working now ")
