### ISSUE TITLE
Conditional Bottom Boundary Error

### ISSUE THREAD

**Issue by ofbodur** [rbeucher/UWGeodynamics#44]
Hello Guys,

I wanted to define conditional bottom bc using the following:

```
ConditionsBottom=fn.branching.conditional([(PoiseuilleFlowModel.x < GEO.nd(-1800.0 * u.kilometer), GEO.nd(25000.0 * u.megapascal)),
                                           (True, GEO.nd(0.0 * u.centimeter / u.year))]) #

PoiseuilleFlowModel.set_velocityBCs(bottom=[0.0 * u.centimeter / u.year, ConditionsBottom],
                                    top=[0.0 * u.centimeter / u.year, None],
                                    right=[0.0 * u.centimeter / u.year, None],
                                    left=[0.0 * u.centimeter / u.year, None])

```
Interestingly, I got the following error:

```
IndexErrorTraceback (most recent call last)
<ipython-input-26-618612d17b79> in <module>()
     23                                     top=[0.0 * u.centimeter / u.year, None],
     24                                     right=[0.0 * u.centimeter / u.year, None],
---> 25                                     left=[0.0 * u.centimeter / u.year, None])

/opt/UWGeodynamics/UWGeodynamics/_model.py in set_velocityBCs(self, left, right, top, bottom, front, back, indexSets)
    739                                        bottom=bottom, front=front,
    740                                        back=back, indexSets=indexSets)
--> 741         return self.velocityBCs.get_conditions()
    742 
    743     set_mechanicalBCs = set_velocityBCs

/opt/UWGeodynamics/UWGeodynamics/_velocity_boundaries.py in get_conditions(self)
    298         for set_ in self.order_wall_conditions:
    299             (condition, nodes) = self._wall_indexSets[set_]
--> 300             self.apply_condition_nodes(condition, nodes)
    301 
    302         if self.indexSets:

/opt/UWGeodynamics/UWGeodynamics/_velocity_boundaries.py in apply_condition_nodes(self, condition, nodes)
    201                     self.Model.velocityField.data[nodes.data, dim] = (
    202                         func.evaluate(
--> 203                             self.Model.mesh.data[nodes.data])[:, dim])
    204                     self.Model.boundariesField.data[nodes.data, dim] = (
    205                         func.evaluate(

IndexError: index 1 is out of bounds for axis 1 with size 1
```

Any idea what is going on?

**Comment by arijitlaik** [comment]
could you send me the full code? if possible, i guess there is something wrong with the x wrt the domian?
laikarijit at gmail is my email id

**Comment by ofbodur** [comment]
Hello @arijitlaik 

I hope the following gives some idea about the domain of the model : 

```
PoiseuilleFlowModel = GEO.Model(minCoord=(-1920. * u.kilometer, -700. * u.kilometer, ),
                  maxCoord=(1920. * u.kilometer, 68. * u.kilometer),  
                  elementRes=(1920, 384),#
                  gravity=(0.0, -9.8 * u.meter / u.second**2))
```

The rest of the code is just rheologies, temperature etc.

**Comment by ofbodur** [comment]
I can define vertical component of the BC at the bottom wall as conditional, but if I make the horizontal component as conditional, it works.

So, the following works:

`bottom=[ConditionsBottom, 0.0 * u.centimeter / u.year],`

but the following does not:

`bottom=[0.0 * u.centimeter / u.year, ConditionsBottom],`

**Comment by arijitlaik** [comment]
yup. same here.

**Comment by ofbodur** [comment]
@rbeucher

**Comment by arijitlaik** [comment]
its possibly because of some corner point problem, as has to do with the order in which boundary conditions are being set. @rbeucher help please.

**Comment by rbeucher** [comment]
Several pbs here:

correct syntax is:

```python
ConditionsBottom= [(PoiseuilleFlowModel.x < GEO.nd(-1800.0 * u.kilometer), GEO.nd(25000.0 * u.megapascal)),
                   (True, GEO.nd(0.0 * u.centimeter / u.year))]

PoiseuilleFlowModel.set_velocityBCs(bottom=[0.0 * u.centimeter / u.year, ConditionsBottom],
                                    top=[0.0 * u.centimeter / u.year, None],
                                    right=[0.0 * u.centimeter / u.year, None],
                                    left=[0.0 * u.centimeter / u.year, None])
```
although the one you used should also work...

There was a bug and 2dac59 fixes it.

However, you are using a mixed condition (Neumann / Dirichlet), you are non-dimensionalizing the values so the code assumes it is all dirichlet (remember I use the units to determine if it a stress or a velocity)... At some point we should be able to do that but we first need to ditch GEO.nd and I don't have an elegant solution yet...

So the solution is to use the indexSets.

The boundaries are processed following the order given by order_wall_conditions but the indexSets are always applied last. I think the neumann condition overwrite Dirichlet in Underworld so defining a dirichlet condition everywhere at the bottom and then an IndexSet with neumann should work...

If it doesnt you can define 2 indexSets, one Dirichlet, one Neumann....

good luck

**Comment by rbeucher** [comment]
For that kind of problem we are touching the limits of UWGeo and it might be better to do it explicitly using pure underworld functionalities... Have a look at the Underworld documentation Omer, that's the best way to learn!

**Comment by julesghub** [comment]
@rbeucher this isn't really about the above but it's related.
What do you think about renaming set_velocityBCs() to something like set_momentumEqBCs(). The fact that velocities and tractions can be defined isn't represented by the current function name.

**Comment by rbeucher** [comment]
There is set_mechanicalBcs as an alias... I agree the name is not good.
@ofbodur What do you prefer: set_velocityBCs(), set_momentumEqBCs(), set_mechanicalBCs
