### ISSUE TITLE
Raijin dev-version update

### ISSUE THREAD

**Issue by ofbodur** [rbeucher/UWGeodynamics#46]
Hello Romain,

In each time you make an update on the development version of the UWGeodynamics, does it mean that the Raijin is also updated? If not, should i update it by myself, maybe weekly ?

Cheers
Omer

**Comment by rbeucher** [comment]
The docker images are updated automatically, you have to update on raijin. 
just cd into the UWGeodynamics folder and do:

```python
git pull
```
