### ISSUE TITLE
Penalty value and Residual

### ISSUE THREAD

**Issue by ofbodur** [rbeucher/UWGeodynamics#47]
Hello Romain, 

I am running a model with thermal anomaly defined as 100 K higher than the ambient asthenosphere. The residual for the non-linear solver is sometimes 500, 1.3, 0.4, so much varies. The tolerance is 0.01 for the model, so convergence takes a bit of time. In fact, it did not converge yet after 100 iteration with 80 CPUs, 2km resolution using 1920x384 mesh,  1.0 cm/yr maximum wall velocity, and penalty value of 1e6, on Raijin.

My question is, can penalty value force the calculation to be rough and give high residuals in each calculation?

**Comment by rbeucher** [comment]
no

**Comment by julesghub** [comment]
The penalty value modifies the "linear" solve method not the non linear (picard iteration) scheme. 
Reduce the complexity of the model to gain insights into the convergence behaviour, i.e. simpler viscosity contrasts, simpler boundary conditions.
