### ISSUE TITLE
How to plot Variable field v.s Depth in UWGeodyanmic

### ISSUE THREAD

**Issue by cgw0814** [rbeucher/UWGeodynamics#54]
Hi, I wonder how to plot Variable field v.s depth fig, like temperature field, viscosity, yield stress...etc. v.s depth fig in GEO?

**Comment by rbeucher** [comment]
The Melt Tutorial shows some examples of temperature / pressure profiles using passive tracers.
I still have to write some examples to show how it can be done for other fields.
The data are available using the data attributes of each field. Then the user is pretty much free to use whatever he/she is comfortable to use for plotting. Matplotlib etc...

**Comment by cgw0814** [comment]
Thank you, I'm trying now, yesterday I tried to use interface before I found the tutorial-2.
