### ISSUE TITLE
Issue with lithostatic pressure

### ISSUE THREAD

**Issue by LukeMondy** [rbeucher/UWGeodynamics#61]
In many of the UW2 notebooks, they say something like this:

>> # Note: the use of a pressure-sensitive rheology suggests that it is important to use a Q2/dQ1 element 
(source: 
https://github.com/underworldcode/underworld2/blob/debf718d3d3275ba3b6cdd8303b277a41463fe47/docs/development/models_broken/LemialeEtAl2008/data_comp/Lemiale-Parallel.py#L122 )

However, when you try to turn this on, the lithostatic pressure function fails, as it is unable to broadcast numpy arrays of different sizes.
```
In func SystemLinearEquations_NonLinearExecute: Converged after 1 iterations.
Traceback (most recent call last):
  File "lmondy_rift.py", line 142, in <module>
    Model.init_model()
  File "/opt/UWGeodynamics/UWGeodynamics/_model.py", line 1460, in init_model
    self.get_lithostatic_pressureField()
  File "/opt/UWGeodynamics/UWGeodynamics/_model.py", line 1361, in get_lithostatic_pressureField
    self.pressureField.data[:], LPressBot = lithoPress.solve()
ValueError: could not broadcast input array from shape (4500,1) into shape (18000,1)

```

Looking at the LithoPress code, I had a go at trying to interpolate the pressure result to the bigger dQ1 array, but got caught up in MPI stuff - but perhaps easier would be to project the density variable on to the subMesh (see here: https://github.com/rbeucher/UWGeodynamics/blob/master/UWGeodynamics/lithopress/lithopress.py#L34 ). 

I had an attempt myself:
```
 lithoPress = LithostaticPressure(self.mesh.subMesh, self._densityFn, gravity)
 # from https://github.com/rbeucher/UWGeodynamics/blob/master/UWGeodynamics/_model.py#L1405
```
but there seems to be some strange differences between the self.mesh and the self.mesh.subMesh - mostly in that they don't have access to the same properties (maybe because the self.mesh is a UWGeodynamics.Underworld_extended._mesh.FeMesh_Cartesian object, while the subMesh is underworld.mesh._mesh.FeMesh)

This seems fairly important, as most of the stuff in UWGeodyamics does use pressure-sensitive rheologies, and in my models I'm seeing a lot of the checker-board pressure. Going to Q2/dQ0 made the model much more stable (in terms of convergence), but then fails because it's not an appropriate element for the _phi field.

Any help would be much appreciated!

**Comment by LukeMondy** [comment]
DruckerPrager (and other) yielding rheologies also depend on the pressure, so it comes up a lot there too.

**Comment by rbeucher** [comment]
I have fixed the function. It can now accept dQ0 and dQ1. It won't work for dpc1.
I tried to mixed Q2/Q1 but it looks like Underworld do not accept that configuration.
I suspect this is a bug and I will ask Julian and John about that.
For now I have limited the lithopress function to dQ0 and dQ1.. I think that's good enough.

I close this one but feel free to reopen if needed. Note that this is just for the lithostatic pressure, I have not tested all the other functions...Will do that asap.
