### ISSUE TITLE
Access to the solver

### ISSUE THREAD

**Issue by LukeMondy** [rbeucher/UWGeodynamics#62]
Hello,

It would be very useful to be able to be able to pass options to the solver from UWGeodynamics.
Either getting access to the solver object like: `Model.solver.options...` or being able to set a method would be good:
```
def options(solver):
    solver.option.whatever = 'ok'
    return solver

Model.set_solver_callback(options)
```

Not quite sure on the details, but something like that would be great!

**Comment by arijitlaik** [comment]
#49 also demands the same :)

**Comment by LukeMondy** [comment]
Fix merged
