### ISSUE TITLE
Issue with new version on Magnus

### ISSUE THREAD

**Issue by LukeMondy** [rbeucher/UWGeodynamics#68]
On magnus, I used shifter the pull the latest underworld_geodynamics:magnus, and tried to start a job.

It reported an issue in initialising the UWGeo module, saying http.client not found.

I will attach the error in a little bit - can't access Magnus where I am - but I think any model would trigger this issue.

**Comment by rbeucher** [comment]
I moved the magnus image to python3... I am still checking things but It's too much work to keep both versions. The image should be ready in 30-60min

**Comment by LukeMondy** [comment]
Yep, seems to have fixed it! Thanks.
